// <auto-generated />
namespace Miles.Sample.Persistence.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IncomingMessageQueueName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IncomingMessageQueueName));
        
        string IMigrationMetadata.Id
        {
            get { return "201612190142036_IncomingMessageQueueName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
